[project]
name = "openrlhf-cu124-demo"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "torch==2.6.0",
    "transformers~=4.56.1",
    "flash-attn==2.7.4.post1",
    "vllm==0.8.5.post1",
    "flashinfer-python==0.2.5",
    "deepspeed==0.17.5",
    "liger_kernel==0.6.2",
    "openrlhf",
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]
deepspeed = [{ requirement = "torch", match-runtime = true }]

[tool.uv.extra-build-variables]
flash-attn = { FLASH_ATTENTION_SKIP_CUDA_BUILD = "TRUE" }

[[tool.uv.dependency-metadata]]
name = "openrlhf"
version = "0.8.11"
requires-dist = [
    # install_requires
    "accelerate",
    "bitsandbytes",
    "datasets",
    "deepspeed==0.17.5",
    "einops",
    # degrade the flash-attn
    # "flash-attn==2.8.3",
    "flash-attn==2.7.4.post1",
    "grpcio>=1.74.0",
    "isort",
    "jsonlines",
    "loralib",
    "optimum",
    "optree>=0.13.0",
    "packaging",
    "peft",
    "pynvml>=12.0.0",
    # degrade the ray[default] for compatibility with vllm==0.8.5.post1
    # "ray[default]==2.48.0",
    "ray[default]==2.47.1",
    "tensorboard",
    "torch",
    "torchdata",
    "torchmetrics",
    "tqdm",
    "transformers==4.56.1",
    "transformers_stream_generator",
    "wandb",
    "wheel",
    # extra_require
    "vllm==0.10.2; extra == 'vllm'",
    "vllm>0.10.2; extra == 'vllm_latest'",
    "ring_flash_attn; extra == 'ring_flash_attn'",
    "liger_kernel; extra == 'liger_kernel'",
]
provides-extras = ["vllm", "vllm_latest", "ring", "liger"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
# https://github.com/OpenRLHF/OpenRLHF/tree/35d12c7846dc37fd2f05f3c79ea4a5f0677ed1c4
openrlhf = { path = "OpenRLHF", editable = true }

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
# url = "https://mirrors.nju.edu.cn/pytorch/whl/cu124"
explicit = true
